#INFOS
NAME = ft_display_file
FILES = ft_display_file.c

#COMPILATION
FLAGS = -Wall -Werror -Wextra
CC = gcc

#RULES

all : comp

comp :
	$(CC) $(FLAGS) -o $(NAME) $(FILES)

clean :
	rm -rf *.o

fclean : clean
	rm -rf $(NAME)